services:
    tahmkenchwiki:
        image: mediawiki:1.45.3
        container_name: tahmkenchwiki
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - wiki
            - nginx
        volumes:
            - ./data/images:/var/www/html/images
            - ./branding:/var/www/html/resources/branding:ro
            - ./datadragon:/datadragon:ro
            - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
            - ./skins/mediawiki-skins-Citizen:/var/www/html/skins/Citizen:ro
            - ./extensions/HeadScript:/var/www/html/extensions/HeadScript:ro
            - ./robot.txt:/var/www/html/robot.txt:ro
    database:
        image: mariadb:latest
        container_name: tahmkenchwiki-db
        restart: always
        env_file:
            - .env
        networks:
            - wiki
        volumes:
            - ./data/db:/var/lib/mysql

    # fix volume owner
    volume-fixer:
        image: mediawiki:1.45.3
        container_name: tahmkenchwiki-volumefixer
        user: root
        volumes:
        - ./data/images:/var/www/html/images
        command: chown -R www-data:www-data /var/www/html/images

networks:
    wiki:
    nginx:
        external: true
        name: nginx
