services:
    mediawiki:
        image: mediawiki:latest
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - 8080:80
        networks:
            - wiki
        volumes:
            - ./data/images:/var/www/html/images
            - ./LocalSettings.php:/var/www/html/LocalSettings.php
        depends_on:
            database:
                condition: service_healthy
    database:
        image: mariadb:latest
        restart: always
        env_file:
            - .env
        networks:
            - wiki
        volumes:
            - ./data/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=${MARIADB_ROOT_PASSWORD}"]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    wiki:
